import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "@/components/footer/Footer";
import NavBar from "@/components/navbar/NavBar";
import NavBarBottom from "@/components/navbarbottom/NavBarBottom";
import HeaderSection from "@/components/headersection/HeaderSection";
import Intro from "@/components/intro/Intro";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Tin Dev | Personal Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Intro />
        <NavBar />
        <NavBarBottom />
        {children}
        <Footer />
      </body>
    </html>
  );
}
